import numpy as np
import matplotlib.pyplot as plt

data3_standard = np.loadtxt('Standard/dados3.txt', dtype='float64', unpack=True)
data4_standard = np.loadtxt('Standard/dados4.txt', dtype='float64', unpack=True)
data6_standard = np.loadtxt('Standard/dados6.txt', dtype='float64', unpack=True)
data8_standard = np.loadtxt('Standard/dados8.txt', dtype='float64', unpack=True)

data3_Numba = np.loadtxt('Numba/dados3.txt', dtype='float64', unpack=True)
data4_Numba = np.loadtxt('Numba/dados4.txt', dtype='float64', unpack=True)
data6_Numba = np.loadtxt('Numba/dados6.txt', dtype='float64', unpack=True)
data8_Numba = np.loadtxt('Numba/dados8.txt', dtype='float64', unpack=True)

len3 = min((data3_standard.shape[1], data3_Numba.shape[1]))
len4 = min((data4_standard.shape[1], data4_Numba.shape[1]))
len6 = min((data6_standard.shape[1], data6_Numba.shape[1]))
len8 = min((data8_standard.shape[1], data8_Numba.shape[1]))


plt.figure(1, figsize=(12.8, 9.6))
plt.subplot(221)
plt.plot(data3_standard[0, 0:len3], data3_Numba[0, 0:len3], 'ko', ms=3)
plt.plot(data3_standard[1, 0:len3], data3_Numba[1, 0:len3], 'rs', ms=3)
plt.plot(data3_standard[2, 0:len3], data3_Numba[2, 0:len3], 'bv', ms=3)
plt.plot([0, 1e-4], [0, 1e-4], 'k--')
plt.xlabel('Pure Python', fontsize=14)
plt.ylabel('Numba', fontsize=14)
plt.text(1e-5, 8e-5, '$V=1x10^{-16}$ L', fontsize=14)
plt.xlim(left=0, right=1e-4)
plt.ylim(bottom=0, top=1e-4)
plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))

plt.subplot(222)
plt.plot(data4_standard[0, 0:len4], data4_Numba[0, 0:len4], 'ko', ms=3)
plt.plot(data4_standard[1, 0:len4], data4_Numba[1, 0:len4], 'rs', ms=3)
plt.plot(data4_standard[2, 0:len4], data4_Numba[2, 0:len4], 'bv', ms=3)
plt.plot([0, 1e-4], [0, 1e-4], 'k--')
plt.xlabel('Pure Python', fontsize=14)
plt.ylabel('Numba', fontsize=14)
plt.text(1e-5, 8e-5, '$V=5x10^{-16}$ L', fontsize=14)
plt.xlim(left=0, right=1e-4)
plt.ylim(bottom=0, top=1e-4)
plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))

plt.subplot(223)
plt.plot(data6_standard[0, 0:len6], data6_Numba[0, 0:len6], 'ko', ms=3)
plt.plot(data6_standard[1, 0:len6], data6_Numba[1, 0:len6], 'rs', ms=3)
plt.plot(data6_standard[2, 0:len6], data6_Numba[2, 0:len6], 'bv', ms=3)
plt.plot([0, 1e-4], [0, 1e-4], 'k--')
plt.xlabel('Pure Python', fontsize=14)
plt.ylabel('Numba', fontsize=14)
plt.text(1e-5, 8e-5, '$V=1x10^{-15}$ L', fontsize=14)
plt.xlim(left=0, right=1e-4)
plt.ylim(bottom=0, top=1e-4)
plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))

plt.subplot(224)
plt.plot(data8_standard[0, 0:len8], data8_Numba[0, 0:len8], 'ko', ms=3)
plt.plot(data8_standard[1, 0:len8], data8_Numba[1, 0:len8], 'rs', ms=3)
plt.plot(data8_standard[2, 0:len8], data8_Numba[2, 0:len8], 'bv', ms=3)
plt.plot([0, 1e-4], [0, 1e-4], 'k--')
plt.xlabel('Pure Python', fontsize=14)
plt.ylabel('Numba', fontsize=14)
plt.text(1e-5, 8e-5, '$V=5x10^{-15}$ L', fontsize=14)
plt.xlim(left=0, right=1e-4)
plt.ylim(bottom=0, top=1e-4)
plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))

plt.savefig('comp.eps', dpi=1000)
plt.show()
